### ISSUE TITLE
version not supported

### ISSUE THREAD

**Issue by morisok31** [Pix3lPirat3/mineprompt_rewritten#1]
whenever i try to join a server, any server, i get this one annoying error:

```
MinePrompt » The version undefined is unsupported, try a supported version.
Supported Versions: 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20
Tested Versions: 1.8.8, 1.9.4, 1.10.2, 1.11.2, 1.12.2, 1.13.2, 1.14.4, 1.15.2, 1.16.5, 1.17.1, 1.18.2, 1.19, 1.19.2, 1.19.3, 1.19.4, 1.20.
1
```

 does anyone know how to fix it?

btw _most_ of the servers are hosted on 1.19.4 OR 1.20.1

**Comment by morisok31** [comment]
ok nvm i fixed it somehow

**Comment by morisok31** [comment]
oke, borken again, it worked for a split second and broke again

**Comment by morisok31** [comment]
also when adding an account:

```
account add [username] authentication true
```

it keep saying that the authentication value has to be either true or false, even though it was true

**Comment by morisok31** [comment]
ok i figured it out with adding the account but still not with the original version issue

**Comment by Pix3lPirat3** [comment]
What's the command you're using? I know I did a janky quick fix for 1.20 or a similar version, project needs to be cleaned up which I keep going back and forth with

**Comment by Pix3lPirat3** [comment]
> also when adding an account:
> 
> 
> 
> ```
> 
> account add [username] authentication true
> 
> ```
> 
> 
> 
> it keep saying that the authentication value has to be either true or false, even though it was true

I think I changed something in this and never tested it..

**Comment by morisok31** [comment]
what do you mean by what version? like for example `-v 1.20` ? or the version of the program

**Comment by Pix3lPirat3** [comment]
> what do you mean by what version? like for example `-v 1.20` ? or the version of the program

What is the command you're using to `connect` eg; `connect -u Username -a true -v 1.19.2`

**Comment by morisok31** [comment]
i am using `connect -u [username] -a true -v 1.20 -h [server-ip]`

**Comment by morisok31** [comment]
soooo, what a i supposed to do then?

**Comment by WhoTho** [comment]
have you updated your repo? the temp patch pixel did works for me. also, does it still say `The version undefined is unsupported, try a supported version.` or does it say `The version 1.2 is unsupported, try a supported version.`

**Comment by morisok31** [comment]
I am going to update the repo i am using now and check if it works

**Comment by morisok31** [comment]
everything isworking fine now, thanks for all help
